From  192.168.2.190:5000/admin/python-flask-test:v1   
WORKDIR  /app
ADD .  /app     
RUN pip  install -r  requirements.txt        
EXPOSE 80                         
ENV  NAME World                
CMD ["python","app.py"]         
